In [1]:
import pandas as pd
import numpy as np

Criando Ndarrays

In [9]:
data1 = [6,7.6,8,0,1]
arr1 = np.array(data1)

In [10]:
arr1

array([6. , 7.6, 8. , 0. , 1. ])

In [12]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)

In [13]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr2.ndim

2

In [16]:
arr2.shape

(2, 4)

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int64')

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
np.empty((2,3,2))

array([[[6.90031313e-310, 4.65976486e-310],
        [0.00000000e+000, 0.00000000e+000],
        [2.37151510e-322, 5.53353523e-322]],

       [[4.65976485e-310, 6.23512027e-085],
        [7.05315400e-297, 5.04267560e+223],
        [4.78104776e+180, 6.24020631e-085]]])

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Tipo de dados para ndarrays

In [23]:
array1 = np.array([1, 2, 3], dtype=np.float64)

In [24]:
array2 = np.array([1, 2, 3], dtype=np.float32)

In [25]:
array1.dtype

dtype('float64')

In [ ]:
array